// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type ApiKey struct {
	ID         uuid.UUID    `json:"id"`
	UserID     uuid.UUID    `json:"user_id"`
	Key        string       `json:"key"`
	Name       string       `json:"name"`
	CreatedAt  time.Time    `json:"created_at"`
	LastUsedAt sql.NullTime `json:"last_used_at"`
	IsActive   bool         `json:"is_active"`
}

type Notification struct {
	ID          uuid.UUID    `json:"id"`
	UserID      uuid.UUID    `json:"user_id"`
	Channel     string       `json:"channel"`
	Message     string       `json:"message"`
	Status      string       `json:"status"`
	CreatedAt   time.Time    `json:"created_at"`
	DeliveredAt sql.NullTime `json:"delivered_at"`
}

type User struct {
	ID           uuid.UUID `json:"id"`
	Email        string    `json:"email"`
	PasswordHash string    `json:"password_hash"`
	CreatedAt    time.Time `json:"created_at"`
}
